apiVersion: 1

datasources:
  - name: InfluxDB-IoT
    uid: influx-iot
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
